In [2]:
import pickle
import pandas as pd

In [11]:
with open("./s_modeldfs.pkl", "rb") as f:
    models = pickle.load(f)

In [17]:
truthlist = [df.isnull().values.any() for df in models]

In [12]:
len(models)

178

In [20]:
nan_index = []
for i in xrange(len(truthlist)):
    if truthlist[i]:
        nan_index.append(i)
        

In [24]:
nan_models =  [models[i] for i in nan_index]

In [13]:
with open("./s_lawmakers.pkl", "rb") as f:
    slawm = pickle.load(f)

In [13]:
from sklearn import datasets, linear_model
from sklearn.model_selection import cross_val_score
diabetes = datasets.load_diabetes()
X = diabetes.data[:150]
y = diabetes.target[:150]
lasso = linear_model.Lasso()
print(cross_val_score(lasso, X, y))

[ 0.33150734  0.08022311  0.03531764]


In [34]:
[ind for ind, df in enumerate(models) if df.isnull().values.any()]

[]

In [15]:
type(slawm)

collections.defaultdict

In [80]:
with open("./h_meanscores.pkl", "rb") as f:
    hmeanscores = pickle.load(f)

In [82]:
hmeanscores = [i for i in hmeanscores if i is not None]

In [83]:
len(hmeanscores)

853

In [39]:
y=0.0
for x in hmeanscores:
   y+=x
y/862

0.78014107030615498

In [84]:
min(hmeanscores)

0.53301673450927178

In [85]:
avg(hmeanscores)

0.779316066081438

In [42]:
(.99+.53)/2

0.76

In [8]:
with open("./s_meanscores.pkl", "rb") as f:
    smeanscores = pickle.load(f)

In [72]:
nsmeanscores = [i for i in smeanscores if i is not None]

In [75]:
avg(nsmeanscores)

0.80065534726736265

In [17]:
overnine = [i for i, x in enumerate(smeanscores) if x > .89]

In [18]:
modelsoverninety=[models[i] for i in overnine]

In [29]:
modeloverninetyrowcount = [mod.shape[0] for mod in modelsoverninety]

In [30]:
modeloverninetyrowcount

[73,
 73,
 54,
 79,
 92,
 73,
 73,
 73,
 73,
 73,
 54,
 54,
 149,
 79,
 128,
 128,
 79,
 204,
 79,
 92,
 54,
 185]

In [52]:
def listswiththreshold(comparison, meanlist, models):
    withresh = [i for i, x in enumerate(meanlist) if comparison(x)]
    modelwithresh = [models[i] for i in withresh]
    modelwithreshrowc = [mod.shape[0] for mod in modelwithresh]
    
    return withresh, modelwithresh, modelwithreshrowc
    

In [53]:
overinds, overninety, overninetyroc = listswiththreshold(lambda x: x > .89, smeanscores, models)

In [62]:
underinds, undersixty, undersixtyroc = listswiththreshold(lambda x: x < .7, smeanscores, models)

In [63]:
undersixtyroc

[128,
 198,
 25,
 25,
 185,
 119,
 185,
 204,
 223,
 223,
 223,
 81,
 149,
 257,
 128,
 277,
 79,
 252,
 204,
 277,
 128,
 277,
 92,
 149,
 101,
 145]

In [102]:
betinds, bet, betroc = listswiththreshold(lambda x : x > .76 and x < .8, smeanscores, models)

In [65]:
betroc

[277,
 252,
 204,
 125,
 198,
 198,
 25,
 73,
 277,
 277,
 166,
 124,
 149,
 128,
 81,
 277,
 223,
 247,
 223,
 277,
 277,
 277,
 92,
 92,
 204,
 277,
 54,
 223,
 223,
 223,
 277,
 54,
 277,
 185,
 124,
 185,
 124,
 149,
 149,
 149,
 277,
 182,
 277,
 277,
 277,
 54,
 277,
 54,
 79,
 128,
 185,
 277,
 277,
 92,
 92,
 149,
 277]

In [66]:
def avg(l):
    y = 0.0
    for x in l:
        y += x
    return y/float(len(l))

In [103]:
avg(betroc)

194.58333333333334

In [68]:
avg(undersixtyroc)

166.69230769230768

In [69]:
avg(overninetyroc)

91.86363636363636

In [77]:
ls 

1to3cvect.pkl                     h_modeldfs.pkl
1to3lda.pkl                       hvotes_p_congress.pkl
2n3ngramsdtmat.pkl                hvotes_per_congress.pkl
2n3ngrams.pkl                     Justshowingsomestuff.ipynb
allbills.pkl                      labeled_bill_request.py
allhbill.pkl                      labeled_bill_request.pyc
allsbill.pkl                      large_topics_lda_out.pkl
all_sbills.pkl                    large_topics_lda.pkl
BillsNTopicsDF.ipynb              lda_out.pkl
billsntopics.pkl                  lda.pkl
build_models.py                   lda_training.py
corpus_feature_engineering.ipynb  list-of-topics.pkl
corpus.py                         majority.csv
Corpus reducing.ipynb             make_models.py
CorpusTermPruning.ipynb           make_topics_df.py
CorpusTopicPruning.ipynb          make_vote_df.py
countandpack.py                   README.md
countvectorizer.pkl               resource_paths.py
cvect2n3.pkl                      resource_paths.pyc
data/  

In [18]:
with open("./s_lawmakerstomodels.pkl", "rb") as f:
    lawmtomod = pickle.load(f)

In [19]:
len(lawmtomod)

178

In [7]:
len(models)

178

In [9]:
len(smeanscores)

178

In [17]:
smeanscores

[0.77295055821371617,
 0.64061538461538459,
 0.83400673400673409,
 0.75800000000000001,
 0.84388603988603994,
 0.79902439024390248,
 0.87223076923076914,
 0.73710256410256403,
 0.77243589743589747,
 0.67552631578947364,
 0.83333333333333326,
 0.88825641025641011,
 0.79789473684210521,
 0.82328330206378975,
 0.70999999999999996,
 0.84000000000000008,
 0.95999999999999996,
 0.80000000000000004,
 0.78142857142857136,
 0.85011904761904766,
 0.88857142857142846,
 0.94666666666666666,
 0.87333333333333341,
 0.86649350649350654,
 0.77977633477633479,
 0.7255483405483405,
 0.8613725490196078,
 0.84000000000000008,
 None,
 0.80706327985739745,
 0.76470588235294112,
 0.85926887926887918,
 0.83255469039673713,
 0.82424242424242422,
 0.71046153846153848,
 0.72528735632183905,
 None,
 0.80000000000000004,
 0.72646153846153838,
 0.61609767662399251,
 0.74039215686274518,
 0.87333333333333341,
 0.77977873977873979,
 0.6660869565217391,
 0.84334597755650376,
 0.92727272727272736,
 0.94999999999999996,

In [24]:
tdf = pd.DataFrame({"one":[.5, .2], "response" : [0, 1]}, index=["a", "b"])

In [34]:
with open("./svotes_p_congress.pkl","rb") as f:
    svotpc =  pickle.load(f)

In [31]:
tdf.columns.values.tolist()

['one', 'response']

In [32]:
def score_topics(df):
    keys = df.columns.values.tolist()
    del keys[-1]
    topicscore = [(df[key] * df["response"]).sum() for key in keys]
    
    return topicscore    

In [41]:
svotpc[0][svotpc[0]["2017s-state"] == "WA"]

2017s-display_name 2017s-party 2017s-state  2017s-hjres43  2017s-s89  \
S229      Murray (D-WA)           D          WA            0.0        0.0   
S275    Cantwell (D-WA)           D          WA            0.0        0.0   

      2017s-hjres66  2017s-hr244  2017s-sres176  2017s-s722  2017s-hr3364  \
S229            0.0          1.0            1.0         1.0           1.0   
S275            0.0          1.0            1.0         1.0           1.0   

        ...     2017s-hjres37  2017s-hjres44  2017s-hjres58  2017s-hjres57  \
S229    ...               0.0            0.0            0.0            0.0   
S275    ...               0.0            0.0            0.0            0.0   

      2017s-hjres42  2017s-hjres69  2017s-hjres83  2017s-sjres34  \
S229            0.0            0.0            0.0            0.0   
S275            0.0            0.0            0.0            0.0   

      2017s-hjres67  congress  
S229            0.0       115  
S275            0.0       115  

[2 rows x 30 columns]

In [42]:
ind = [i for i, x in enumerate(lawmtomod) if x == "S229" or x == "S275"]

In [43]:
ind

[0, 91]

In [44]:
lawmtomod[0]

u'S229'

In [45]:
topicsmurray = score_topics(models[0])

In [46]:
topicscantwell = score_topics(models[91])

In [51]:
import numpy as np

In [52]:
topicsmurray = np.array(topicsmurray)

In [53]:
topicscantwell = np.array(topicscantwell)

In [62]:
srtmurray = np.argsort(topicsmurray)

In [63]:
srtcantwell = np.argsort(topicscantwell)

In [64]:
topicscantwell[srtcantwell[-1]]

12.602557026905252

In [65]:
topfivemurray = srtmurray[-5:]

In [68]:
topfivecantwell = srtcantwell[-5:]

In [72]:
topfivemurray

array([42, 17, 15, 35, 53])

In [73]:
topfivecantwell

array([42, 15, 12, 35, 53])

In [81]:
botfivemurray = srtmurray[11:16]
botfivecantwell  = srtcantwell[11:16]

In [82]:
botfivecantwell

array([50, 37, 10,  1,  8])

In [83]:
botfivemurray

array([ 1, 50, 32, 30, 37])